### ISSUE TITLE
erste GUI Elemente vorhanden

### ISSUE THREAD

**Issue by David-Koellnberger** [srn-gruppe-2015/srn-semesterarbeit#1]
Erste Views sind jetzt da (Login und neuer-Benutzer-anlege-Dialog. Theoretisch kann schon Logik für das Back-End entworfen werden, was den Login und den neuen Eintrag eines Nutzer angeht (siehe TODOs)

Mit der MainController Realisierung bin ich noch nicht ganz zu frienden. Evtl änder ich da noch was

Ich bin mir nicht sicher ob der commit geklappt hat. Bei mir in Eclipse konnte ich erfolgreich das Projekt auschecken und seh seh auch wer was gemacht hat. In der Historie ist auch mein commit drin nur auf github.com ist es nicht zu sehen.

Als nächstes mache ich die Hauptseite, kann nur sein das ich das Designertool wechseln muss, da der Windows Builder irgendwie Probleme mit Fenster hat die in Vollbild sind.

**Comment by David-Koellnberger** [comment]
okay hat sich erledigt. Ich hatte noch eine veraltete Version. Sachen sind commited

**Comment by dommynik** [comment]
Habe nichts an der GUI-Implementierung auszusetzen! Sieht gut aus. Bitte weiter machen!

**Comment by David-Koellnberger** [comment]
Alles bin noch dabei
