### ISSUE TITLE
Back End Logik

### ISSUE THREAD

**Issue by David-Koellnberger** [srn-gruppe-2015/srn-semesterarbeit#2]
Hallo zusammen,
wer auch immer die Logik im Back End programmiert, kann folgende Funktionalitäten entwickeln damit ich diese dann auch darstellen (bzw. das ich auch meinen Code testen kann):

- (für LoginController): Überprüfung der Logindaten
- (für CreateAccountDialog): Überprüfung, ob der neu registrierte Username noch nicht im System 
                                              vorhanden ist
- (für NewKeyDialog): einen neuen Schlüssel(name) für einen User in das System speichern, davor aber noch überprüfen ob es den Schlüssel(name) noch nicht gibt -> ist auch fertig, muss aber nicht noch nach doppelten Namen überprüft werden oder?

- (für MainPageController):
- (alle Keys von einem Bneutzer -> ist bereits fertig oder? Unter Keybox, getSharedKeys und getKeys)
-> es können Vorkehrungen gereffen werden, bevor das gesamte Programm beendet wird

**Comment by David-Koellnberger** [comment]
Der Loginvorgang müsste jetzt soweit passen.
FRAGE: bei der Registration (neuer Account erstellen) muss das Kopfpasswort auch vom User eingegeben werden richtig? Damit ich dann einen neuen User in das System mit Hilfe der Klasse KeychainManager..registerUser(username, password, headpassword) aufnehmen kann

**Comment by dommynik** [comment]
Passt!

**Comment by dommynik** [comment]
Richtig. :P
Am 04.05.2015 22:09 schrieb David-Koellnberger <notifications@github.com>:Der Loginvorgang müsste jetzt soweit passen.
FRAGE: bei der Registration (neuer Account erstellen) muss das Kopfpasswort auch vom User eingegeben werden richtig? Damit ich dann einen neuen User in das System mit Hilfe der Klasse KeychainManager..registerUser(username, password, headpassword) aufnehmen kann
