### ISSUE TITLE
Treffen am Mittwoch den 6.5?

### ISSUE THREAD

**Issue by David-Koellnberger** [srn-gruppe-2015/srn-semesterarbeit#3]
Hallo zusammen,

wollen wir uns morgen wieder kurz treffen oder ist das zur Zeit nicht notwendig? Wenn ja wieder oben im S Gebäude und wann?

Beste Grüße

**Comment by dommynik** [comment]
Ja, wieder um 13.40 Uhr oben im S-Gebäude.
