### ISSUE TITLE
Treffen 11.05.2015

### ISSUE THREAD

**Issue by dommynik** [srn-gruppe-2015/srn-semesterarbeit#8]
Hey,
Mathias hat mir vorgeschlagen, dass wir uns morgen treffen. Da eigtl. das Projekt heute auf einem relativ fertigen Stand sein sollte, dies aber nicht ist, würde ich dann morgen - ohne David - mir den Tag freinehmen und mit euch ne Programmier-Session machen. Wann habt ihr Zeit?

**Comment by erdi-007** [comment]
also Mathias wollte gleich um 12 Uhr in die HS kommen und wir wollten dann weiter programmieren

**Comment by David-Koellnberger** [comment]
Hallo zusammen. Bei mir gibt es eine Planänderung: ich habe morgen frei und kann jederzeit.

**Comment by David-Koellnberger** [comment]
also morgen denn 12.5. hab ich frei
